image: maven:3-jdk-8

stages:
  - build


JUnit5:
    stage: build
    script: "mvn package"
    artifacts:
        reports:
            junit:
                - target/sure-fire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml